# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiInsert.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class insertDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(695, 265)
        self.gridLayout_3 = QtGui.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.dateLabel = QtGui.QLabel(Dialog)
        self.dateLabel.setObjectName(_fromUtf8("dateLabel"))
        self.gridLayout_3.addWidget(self.dateLabel, 0, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.scrollArea = QtGui.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 595, 136))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.UIDLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.UIDLineEdit.setObjectName(_fromUtf8("UIDLineEdit"))
        self.verticalLayout.addWidget(self.UIDLineEdit)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.placaLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.placaLineEdit.setObjectName(_fromUtf8("placaLineEdit"))
        self.verticalLayout_2.addWidget(self.placaLineEdit)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.descripcionLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.descripcionLineEdit.setObjectName(_fromUtf8("descripcionLineEdit"))
        self.verticalLayout_3.addWidget(self.descripcionLineEdit)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 2, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.serialLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.serialLineEdit.setObjectName(_fromUtf8("serialLineEdit"))
        self.verticalLayout_4.addWidget(self.serialLineEdit)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_5.addWidget(self.label_5)
        self.marcaLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.marcaLineEdit.setObjectName(_fromUtf8("marcaLineEdit"))
        self.verticalLayout_5.addWidget(self.marcaLineEdit)
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 1, 1, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_6.addWidget(self.label_6)
        self.modeloLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.modeloLineEdit.setObjectName(_fromUtf8("modeloLineEdit"))
        self.verticalLayout_6.addWidget(self.modeloLineEdit)
        self.gridLayout.addLayout(self.verticalLayout_6, 1, 2, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 2, 1)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.readButton = QtGui.QPushButton(self.tab)
        self.readButton.setText(_fromUtf8(""))
        self.readButton.setObjectName(_fromUtf8("readButton"))
        self.verticalLayout_7.addWidget(self.readButton)
        self.clearButton = QtGui.QPushButton(self.tab)
        self.clearButton.setText(_fromUtf8(""))
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.verticalLayout_7.addWidget(self.clearButton)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 63, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 1, 0, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(492, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 2, 0, 1, 1)
        self.saveButton = QtGui.QPushButton(Dialog)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.gridLayout_3.addWidget(self.saveButton, 2, 1, 1, 1)
        self.closeButton = QtGui.QPushButton(Dialog)
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.gridLayout_3.addWidget(self.closeButton, 2, 2, 1, 1)
        self.timeLabel = QtGui.QLabel(Dialog)
        self.timeLabel.setObjectName(_fromUtf8("timeLabel"))
        self.gridLayout_3.addWidget(self.timeLabel, 0, 2, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "GUARDAR DATOS", None))
        self.dateLabel.setText(_translate("Dialog", "Fecha", None))
        self.label.setText(_translate("Dialog", "UID:", None))
        self.label_2.setText(_translate("Dialog", "PLACA:", None))
        self.label_3.setText(_translate("Dialog", "DESCRIPCIÓN:", None))
        self.label_4.setText(_translate("Dialog", "SERIAL:", None))
        self.label_5.setText(_translate("Dialog", "MARCA:", None))
        self.label_6.setText(_translate("Dialog", "MODELO:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Ingresar datos", None))
        self.saveButton.setText(_translate("Dialog", "GUARDAR", None))
        self.closeButton.setText(_translate("Dialog", "SALIR", None))
        self.timeLabel.setText(_translate("Dialog", "Hora", None))

