# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiMain.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(916, 555)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_6 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.timeLabel = QtGui.QLabel(self.centralwidget)
        self.timeLabel.setObjectName(_fromUtf8("timeLabel"))
        self.gridLayout_6.addWidget(self.timeLabel, 0, 1, 1, 1)
        self.dateLabel = QtGui.QLabel(self.centralwidget)
        self.dateLabel.setObjectName(_fromUtf8("dateLabel"))
        self.gridLayout_6.addWidget(self.dateLabel, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(775, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 2, 0, 1, 1)
        self.closeButton = QtGui.QPushButton(self.centralwidget)
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.gridLayout_6.addWidget(self.closeButton, 2, 1, 1, 1)
        self.tabWidgetTab = QtGui.QTabWidget(self.centralwidget)
        self.tabWidgetTab.setObjectName(_fromUtf8("tabWidgetTab"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem1 = QtGui.QSpacerItem(771, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.seeMoreButtonTab1 = QtGui.QPushButton(self.tab)
        self.seeMoreButtonTab1.setObjectName(_fromUtf8("seeMoreButtonTab1"))
        self.horizontalLayout_6.addWidget(self.seeMoreButtonTab1)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 1, 0, 1, 4)
        spacerItem2 = QtGui.QSpacerItem(82, 89, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem2, 3, 3, 1, 1)
        self.tableWidgetTab1 = QtGui.QTableWidget(self.tab)
        self.tableWidgetTab1.setObjectName(_fromUtf8("tableWidgetTab1"))
        self.tableWidgetTab1.setColumnCount(0)
        self.tableWidgetTab1.setRowCount(0)
        self.gridLayout_4.addWidget(self.tableWidgetTab1, 0, 0, 1, 4)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 2, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 633, 123))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.antenna1Label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.antenna1Label.setObjectName(_fromUtf8("antenna1Label"))
        self.gridLayout_2.addWidget(self.antenna1Label, 0, 1, 1, 1)
        self.antenna4Label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.antenna4Label.setObjectName(_fromUtf8("antenna4Label"))
        self.gridLayout_2.addWidget(self.antenna4Label, 0, 2, 1, 1)
        self.antenna2Label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.antenna2Label.setObjectName(_fromUtf8("antenna2Label"))
        self.gridLayout_2.addWidget(self.antenna2Label, 1, 1, 1, 1)
        self.antenna5Label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.antenna5Label.setObjectName(_fromUtf8("antenna5Label"))
        self.gridLayout_2.addWidget(self.antenna5Label, 1, 2, 1, 1)
        self.antenna3Label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.antenna3Label.setObjectName(_fromUtf8("antenna3Label"))
        self.gridLayout_2.addWidget(self.antenna3Label, 2, 1, 1, 1)
        self.antenna6Label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.antenna6Label.setObjectName(_fromUtf8("antenna6Label"))
        self.gridLayout_2.addWidget(self.antenna6Label, 2, 2, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 3, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(82, 89, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem3, 3, 0, 1, 1)
        self.tableWidgetTab1.raise_()
        self.label_2.raise_()
        self.scrollArea.raise_()
        self.tabWidgetTab.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.searchLineEditTab2 = QtGui.QLineEdit(self.tab_2)
        self.searchLineEditTab2.setText(_fromUtf8(""))
        self.searchLineEditTab2.setObjectName(_fromUtf8("searchLineEditTab2"))
        self.horizontalLayout_4.addWidget(self.searchLineEditTab2)
        self.clearSearchButtonTab2 = QtGui.QPushButton(self.tab_2)
        self.clearSearchButtonTab2.setText(_fromUtf8(""))
        self.clearSearchButtonTab2.setObjectName(_fromUtf8("clearSearchButtonTab2"))
        self.horizontalLayout_4.addWidget(self.clearSearchButtonTab2)
        spacerItem4 = QtGui.QSpacerItem(288, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.itemTablecomboBoxTab2 = QtGui.QComboBox(self.tab_2)
        self.itemTablecomboBoxTab2.setObjectName(_fromUtf8("itemTablecomboBoxTab2"))
        self.itemTablecomboBoxTab2.addItem(_fromUtf8(""))
        self.itemTablecomboBoxTab2.addItem(_fromUtf8(""))
        self.itemTablecomboBoxTab2.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.itemTablecomboBoxTab2)
        self.searchButtonTab2 = QtGui.QPushButton(self.tab_2)
        self.searchButtonTab2.setText(_fromUtf8(""))
        self.searchButtonTab2.setObjectName(_fromUtf8("searchButtonTab2"))
        self.horizontalLayout_2.addWidget(self.searchButtonTab2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tableViewTab2 = QtGui.QTableView(self.tab_2)
        self.tableViewTab2.setObjectName(_fromUtf8("tableViewTab2"))
        self.horizontalLayout_5.addWidget(self.tableViewTab2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.insertButtonTab2 = QtGui.QPushButton(self.tab_2)
        self.insertButtonTab2.setText(_fromUtf8(""))
        self.insertButtonTab2.setObjectName(_fromUtf8("insertButtonTab2"))
        self.verticalLayout.addWidget(self.insertButtonTab2)
        self.deleteButtonTab2 = QtGui.QPushButton(self.tab_2)
        self.deleteButtonTab2.setText(_fromUtf8(""))
        self.deleteButtonTab2.setObjectName(_fromUtf8("deleteButtonTab2"))
        self.verticalLayout.addWidget(self.deleteButtonTab2)
        self.updateButtonTab2 = QtGui.QPushButton(self.tab_2)
        self.updateButtonTab2.setText(_fromUtf8(""))
        self.updateButtonTab2.setObjectName(_fromUtf8("updateButtonTab2"))
        self.verticalLayout.addWidget(self.updateButtonTab2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem5 = QtGui.QSpacerItem(20, 236, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.tabWidgetTab.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout = QtGui.QGridLayout(self.tab_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.tab_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.searchLineEditTab3 = QtGui.QLineEdit(self.tab_3)
        self.searchLineEditTab3.setText(_fromUtf8(""))
        self.searchLineEditTab3.setObjectName(_fromUtf8("searchLineEditTab3"))
        self.gridLayout.addWidget(self.searchLineEditTab3, 0, 1, 1, 1)
        self.toggleButtonTab3 = QtGui.QPushButton(self.tab_3)
        self.toggleButtonTab3.setObjectName(_fromUtf8("toggleButtonTab3"))
        self.gridLayout.addWidget(self.toggleButtonTab3, 0, 2, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(346, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 3, 1, 3)
        self.label_4 = QtGui.QLabel(self.tab_3)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 6, 1, 1)
        self.serialPortComboBoxTab3 = QtGui.QComboBox(self.tab_3)
        self.serialPortComboBoxTab3.setObjectName(_fromUtf8("serialPortComboBoxTab3"))
        self.serialPortComboBoxTab3.addItem(_fromUtf8(""))
        self.serialPortComboBoxTab3.addItem(_fromUtf8(""))
        self.serialPortComboBoxTab3.addItem(_fromUtf8(""))
        self.serialPortComboBoxTab3.addItem(_fromUtf8(""))
        self.serialPortComboBoxTab3.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.serialPortComboBoxTab3, 0, 7, 1, 1)
        self.tableViewTab3 = QtGui.QTableView(self.tab_3)
        self.tableViewTab3.setObjectName(_fromUtf8("tableViewTab3"))
        self.gridLayout.addWidget(self.tableViewTab3, 1, 0, 3, 4)
        spacerItem7 = QtGui.QSpacerItem(20, 153, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 1, 4, 1, 1)
        self.listWidgetTab3 = QtGui.QListWidget(self.tab_3)
        self.listWidgetTab3.setObjectName(_fromUtf8("listWidgetTab3"))
        self.gridLayout.addWidget(self.listWidgetTab3, 1, 5, 3, 2)
        spacerItem8 = QtGui.QSpacerItem(20, 153, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 1, 7, 1, 1)
        self.selectUIDButtonTab3 = QtGui.QPushButton(self.tab_3)
        self.selectUIDButtonTab3.setObjectName(_fromUtf8("selectUIDButtonTab3"))
        self.gridLayout.addWidget(self.selectUIDButtonTab3, 2, 4, 1, 1)
        self.labelTab3 = QtGui.QLabel(self.tab_3)
        self.labelTab3.setObjectName(_fromUtf8("labelTab3"))
        self.gridLayout.addWidget(self.labelTab3, 2, 7, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 154, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 3, 4, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 154, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem10, 3, 7, 1, 1)
        self.tabWidgetTab.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout_6.addWidget(self.tabWidgetTab, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 916, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArchivo = QtGui.QMenu(self.menubar)
        self.menuArchivo.setObjectName(_fromUtf8("menuArchivo"))
        self.menuSistemas_de_Antenas = QtGui.QMenu(self.menuArchivo)
        self.menuSistemas_de_Antenas.setObjectName(_fromUtf8("menuSistemas_de_Antenas"))
        self.menuAjustes = QtGui.QMenu(self.menubar)
        self.menuAjustes.setObjectName(_fromUtf8("menuAjustes"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionConfiguracio = QtGui.QAction(MainWindow)
        self.actionConfiguracio.setObjectName(_fromUtf8("actionConfiguracio"))
        self.preferencesAction = QtGui.QAction(MainWindow)
        self.preferencesAction.setObjectName(_fromUtf8("preferencesAction"))
        self.scanSerialPortsAction = QtGui.QAction(MainWindow)
        self.scanSerialPortsAction.setObjectName(_fromUtf8("scanSerialPortsAction"))
        self.onOffAction = QtGui.QAction(MainWindow)
        self.onOffAction.setObjectName(_fromUtf8("onOffAction"))
        self.menuSistemas_de_Antenas.addAction(self.onOffAction)
        self.menuArchivo.addAction(self.menuSistemas_de_Antenas.menuAction())
        self.menuAjustes.addAction(self.scanSerialPortsAction)
        self.menuAjustes.addAction(self.preferencesAction)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuAjustes.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidgetTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "BASE DE DATOS", None))
        self.timeLabel.setText(_translate("MainWindow", "Hora", None))
        self.dateLabel.setText(_translate("MainWindow", "Fecha", None))
        self.closeButton.setText(_translate("MainWindow", "Salir", None))
        self.seeMoreButtonTab1.setText(_translate("MainWindow", "...", None))
        self.label_2.setText(_translate("MainWindow", "SISTEMAS DE ANTENNAS", None))
        self.label_5.setText(_translate("MainWindow", "Estado:", None))
        self.antenna1Label.setText(_translate("MainWindow", "Antena 1 / Desactivado", None))
        self.antenna4Label.setText(_translate("MainWindow", "Antena 4 / Desactivado", None))
        self.antenna2Label.setText(_translate("MainWindow", "Antena 2 / Desactivado", None))
        self.antenna5Label.setText(_translate("MainWindow", "Antena 5 /  Desactivado", None))
        self.antenna3Label.setText(_translate("MainWindow", "Antena 3 / Desactivado", None))
        self.antenna6Label.setText(_translate("MainWindow", "Antena 6 /  Desactivado", None))
        self.tabWidgetTab.setTabText(self.tabWidgetTab.indexOf(self.tab), _translate("MainWindow", "Registro", None))
        self.label.setText(_translate("MainWindow", "Buscar:", None))
        self.itemTablecomboBoxTab2.setItemText(0, _translate("MainWindow", "UID", None))
        self.itemTablecomboBoxTab2.setItemText(1, _translate("MainWindow", "Equipo", None))
        self.itemTablecomboBoxTab2.setItemText(2, _translate("MainWindow", "Laboratorio", None))
        self.tabWidgetTab.setTabText(self.tabWidgetTab.indexOf(self.tab_2), _translate("MainWindow", "Inventario", None))
        self.label_3.setText(_translate("MainWindow", "Buscar por UID:", None))
        self.toggleButtonTab3.setText(_translate("MainWindow", "Detectar", None))
        self.label_4.setText(_translate("MainWindow", "Puerto Serial:", None))
        self.serialPortComboBoxTab3.setItemText(0, _translate("MainWindow", "/dev/ttyUSB0", None))
        self.serialPortComboBoxTab3.setItemText(1, _translate("MainWindow", "/dev/ttyUSB1", None))
        self.serialPortComboBoxTab3.setItemText(2, _translate("MainWindow", "/dev/ttyUSB2", None))
        self.serialPortComboBoxTab3.setItemText(3, _translate("MainWindow", "/dev/ttyUSB3", None))
        self.serialPortComboBoxTab3.setItemText(4, _translate("MainWindow", "/dev/ttyUSB4", None))
        self.selectUIDButtonTab3.setText(_translate("MainWindow", "Seleccionar UID:", None))
        self.labelTab3.setText(_translate("MainWindow", "No Disponible", None))
        self.tabWidgetTab.setTabText(self.tabWidgetTab.indexOf(self.tab_3), _translate("MainWindow", "Buscar", None))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo", None))
        self.menuSistemas_de_Antenas.setTitle(_translate("MainWindow", "Sistemas de Antenas", None))
        self.menuAjustes.setTitle(_translate("MainWindow", "Ajustes", None))
        self.actionConfiguracio.setText(_translate("MainWindow", "Ajustes", None))
        self.preferencesAction.setText(_translate("MainWindow", "Preferencias", None))
        self.scanSerialPortsAction.setText(_translate("MainWindow", "Escanear Puertos", None))
        self.onOffAction.setText(_translate("MainWindow", "Activar/Desesactivar", None))

