# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiPortSerial.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class preferencesDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(335, 388)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem = QtGui.QSpacerItem(114, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 293, 247))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.parityComboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.parityComboBox.setObjectName(_fromUtf8("parityComboBox"))
        self.parityComboBox.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.parityComboBox, 3, 1, 1, 1)
        self.baudRateComboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.baudRateComboBox.setObjectName(_fromUtf8("baudRateComboBox"))
        self.baudRateComboBox.addItem(_fromUtf8(""))
        self.baudRateComboBox.addItem(_fromUtf8(""))
        self.baudRateComboBox.addItem(_fromUtf8(""))
        self.baudRateComboBox.addItem(_fromUtf8(""))
        self.baudRateComboBox.addItem(_fromUtf8(""))
        self.baudRateComboBox.addItem(_fromUtf8(""))
        self.baudRateComboBox.addItem(_fromUtf8(""))
        self.baudRateComboBox.addItem(_fromUtf8(""))
        self.baudRateComboBox.addItem(_fromUtf8(""))
        self.baudRateComboBox.addItem(_fromUtf8(""))
        self.baudRateComboBox.addItem(_fromUtf8(""))
        self.baudRateComboBox.addItem(_fromUtf8(""))
        self.baudRateComboBox.addItem(_fromUtf8(""))
        self.baudRateComboBox.addItem(_fromUtf8(""))
        self.baudRateComboBox.addItem(_fromUtf8(""))
        self.baudRateComboBox.addItem(_fromUtf8(""))
        self.baudRateComboBox.addItem(_fromUtf8(""))
        self.baudRateComboBox.addItem(_fromUtf8(""))
        self.baudRateComboBox.addItem(_fromUtf8(""))
        self.baudRateComboBox.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.baudRateComboBox, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.handshakingComboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.handshakingComboBox.setObjectName(_fromUtf8("handshakingComboBox"))
        self.handshakingComboBox.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.handshakingComboBox, 5, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 5, 0, 1, 1)
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.portSerialComboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.portSerialComboBox.setObjectName(_fromUtf8("portSerialComboBox"))
        self.gridLayout_3.addWidget(self.portSerialComboBox, 0, 1, 1, 1)
        self.stopBitsComboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.stopBitsComboBox.setObjectName(_fromUtf8("stopBitsComboBox"))
        self.stopBitsComboBox.addItem(_fromUtf8(""))
        self.stopBitsComboBox.addItem(_fromUtf8(""))
        self.stopBitsComboBox.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.stopBitsComboBox, 4, 1, 1, 1)
        self.dataBitsComboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.dataBitsComboBox.setObjectName(_fromUtf8("dataBitsComboBox"))
        self.dataBitsComboBox.addItem(_fromUtf8(""))
        self.dataBitsComboBox.addItem(_fromUtf8(""))
        self.dataBitsComboBox.addItem(_fromUtf8(""))
        self.dataBitsComboBox.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.dataBitsComboBox, 2, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 2)
        self.defaultButton = QtGui.QPushButton(self.tab)
        self.defaultButton.setObjectName(_fromUtf8("defaultButton"))
        self.gridLayout_2.addWidget(self.defaultButton, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 3)
        self.cancelButton = QtGui.QPushButton(Dialog)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.gridLayout.addWidget(self.cancelButton, 1, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(132, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.acceptButton = QtGui.QPushButton(Dialog)
        self.acceptButton.setObjectName(_fromUtf8("acceptButton"))
        self.gridLayout.addWidget(self.acceptButton, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "PUERTO SERIAL", None))
        self.label_2.setText(_translate("Dialog", "Bits por segundos:", None))
        self.parityComboBox.setItemText(0, _translate("Dialog", "Ninguna", None))
        self.baudRateComboBox.setItemText(0, _translate("Dialog", "110", None))
        self.baudRateComboBox.setItemText(1, _translate("Dialog", "300", None))
        self.baudRateComboBox.setItemText(2, _translate("Dialog", "600", None))
        self.baudRateComboBox.setItemText(3, _translate("Dialog", "1200", None))
        self.baudRateComboBox.setItemText(4, _translate("Dialog", "2400", None))
        self.baudRateComboBox.setItemText(5, _translate("Dialog", "4800", None))
        self.baudRateComboBox.setItemText(6, _translate("Dialog", "9600", None))
        self.baudRateComboBox.setItemText(7, _translate("Dialog", "14400", None))
        self.baudRateComboBox.setItemText(8, _translate("Dialog", "19200", None))
        self.baudRateComboBox.setItemText(9, _translate("Dialog", "28800", None))
        self.baudRateComboBox.setItemText(10, _translate("Dialog", "38400", None))
        self.baudRateComboBox.setItemText(11, _translate("Dialog", "56000", None))
        self.baudRateComboBox.setItemText(12, _translate("Dialog", "57600", None))
        self.baudRateComboBox.setItemText(13, _translate("Dialog", "115200", None))
        self.baudRateComboBox.setItemText(14, _translate("Dialog", "128000", None))
        self.baudRateComboBox.setItemText(15, _translate("Dialog", "153600", None))
        self.baudRateComboBox.setItemText(16, _translate("Dialog", "230400", None))
        self.baudRateComboBox.setItemText(17, _translate("Dialog", "256000", None))
        self.baudRateComboBox.setItemText(18, _translate("Dialog", "460800", None))
        self.baudRateComboBox.setItemText(19, _translate("Dialog", "921600", None))
        self.label_5.setText(_translate("Dialog", "Paridad:", None))
        self.label_6.setText(_translate("Dialog", "Bits de paridad:", None))
        self.label_3.setText(_translate("Dialog", "Bits de datos:", None))
        self.handshakingComboBox.setItemText(0, _translate("Dialog", "Ninguna", None))
        self.label_4.setText(_translate("Dialog", "Control de flujo:", None))
        self.label.setText(_translate("Dialog", "Puerto:", None))
        self.stopBitsComboBox.setItemText(0, _translate("Dialog", "1", None))
        self.stopBitsComboBox.setItemText(1, _translate("Dialog", "1.5", None))
        self.stopBitsComboBox.setItemText(2, _translate("Dialog", "2", None))
        self.dataBitsComboBox.setItemText(0, _translate("Dialog", "5", None))
        self.dataBitsComboBox.setItemText(1, _translate("Dialog", "6", None))
        self.dataBitsComboBox.setItemText(2, _translate("Dialog", "7", None))
        self.dataBitsComboBox.setItemText(3, _translate("Dialog", "8", None))
        self.defaultButton.setText(_translate("Dialog", "Restaurar predeterminado", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Configuracion de puerto", None))
        self.cancelButton.setText(_translate("Dialog", "Cancelar", None))
        self.acceptButton.setText(_translate("Dialog", "Aceptar", None))

